"""
AgriNova AI — AI Service.

Orchestrates the AI conversation flow with persistent conversations
and farm-contextual awareness.

Phase 2 flow (conversation persistence):
  1. Load or create conversation.
  2. Load existing message history BEFORE adding the new message.
  3. Save the new user message to DB.
  4. Build LLM messages: system prompt + existing history + new user message.
  5. Call LLM provider.
  6. Save assistant response to DB.
  7. Update conversation title/timestamp.

Phase 3 additions (context engine):
  - Resolve farm_id from request / conversation with locking rules.
  - Build UnifiedContext via ContextService.
  - Format context via ContextFormatter.
  - Inject formatted context into the system prompt.

Farm locking rules:
  ┌─────────────────┬─────────────────┬────────────────────┐
  │ Conversation     │ Request          │ Result             │
  │ farm_id          │ farm_id          │                    │
  ├─────────────────┼─────────────────┼────────────────────┤
  │ A                │ A                │ ✅ use A            │
  │ A                │ B                │ ❌ 409 Conflict     │
  │ A                │ None             │ ✅ use A            │
  │ None             │ A                │ ✅ lock to A        │
  │ None             │ B                │ ✅ lock to B        │
  │ None             │ None             │ ✅ no farm context  │
  └─────────────────┴─────────────────┴────────────────────┘

On LLM failure:
  - The user message is persisted (useful for retry).
  - No assistant message is saved.
  - A normalized provider error is raised.

System prompt:
  - Generated by the prompt layer at request time.
  - NOT persisted as a conversation message.
"""

import logging

from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.providers.base import AIMessage, BaseAIProvider
from app.ai.providers.gemini import GeminiProvider
from app.ai.providers.openrouter import OpenRouterProvider
from app.ai.providers.manager import AIProviderManager
from app.ai.prompts.system import AIRA_SYSTEM_PROMPT
from app.ai.schemas.chat import ChatRequest, ChatResponse
from app.ai.services.context_service import ContextService
from app.ai.services.context_formatter import format_context
from app.core.config import settings
from app.core.exceptions import ConflictException, NotFoundException
from app.models.conversation import Conversation, Message
from app.models.farm import Farm
from app.repositories.conversation_repo import ConversationRepository
from app.repositories.farm_repo import FarmRepository
from app.ai.services.token_budget import PRACTICAL_CONTEXT_BUDGET, OUTPUT_RESERVE, estimate_tokens
from app.ai.services.history_manager import HistoryManager

logger = logging.getLogger(__name__)

# ── Title generation ────────────────────────────────────────────────────────
_MAX_TITLE_LENGTH = 50


def _generate_title(first_message: str) -> str:
    """Create a conversation title from the first user message.

    Simple truncation — no Gemini call.  Keeps it cheap and fast.
    """
    title = first_message.strip().replace("\n", " ")
    if len(title) > _MAX_TITLE_LENGTH:
        title = title[:_MAX_TITLE_LENGTH].rstrip() + "…"
    return title


class AIService:
    """High-level AI service used by the API layer.

    Phase 3: adds farm resolution, context building, and context-aware
    prompt assembly.
    """

    def __init__(self, db: AsyncSession) -> None:
        self.db = db
        self.repo = ConversationRepository(db)
        self.farm_repo = FarmRepository(db)
        self.context_service = ContextService(db)
        self._provider: BaseAIProvider | None = None

    def _get_provider_manager(self) -> BaseAIProvider:
        """Lazy-initialize the AI provider manager.

        Only called when ``chat()`` needs the provider, so conversation
        CRUD operations work even without a valid Gemini API key.
        """
        if self._provider is None:
            providers = []
            
            gemini = GeminiProvider(
                api_key=settings.GEMINI_API_KEY,
                model_name=settings.AI_MODEL_NAME,
            )
            providers.append(gemini)
            
            if settings.AI_ENABLE_FALLBACK and settings.OPENROUTER_API_KEY and settings.OPENROUTER_MODEL_NAME:
                openrouter = OpenRouterProvider(
                    api_key=settings.OPENROUTER_API_KEY,
                    model_name=settings.OPENROUTER_MODEL_NAME,
                )
                providers.append(openrouter)
                
            self._provider = AIProviderManager(providers=providers)
            
        return self._provider

    async def chat(self, user_id: str, request: ChatRequest) -> ChatResponse:
        """Process a chat request with conversation persistence and farm context.

        Args:
            user_id: Authenticated user's ID.
            request: Validated ``ChatRequest`` (message + optional conversation_id + farm_id).

        Returns:
            ``ChatResponse`` with Aira's reply and the conversation ID.
        """
        # 1. Load or create conversation
        conversation = await self._resolve_conversation(user_id, request.conversation_id)

        # 2. Resolve and validate farm_id (locking rules)
        farm = await self._resolve_farm(user_id, conversation, request.farm_id)

        # 3. Build context (if farm is available)
        context_string = ""
        if farm:
            unified_context = await self.context_service.build_unified_context(
                farm, user_message=request.message
            )
            context_string = format_context(unified_context)

        # 4. Load existing message history BEFORE adding the new message
        existing_messages = await self.repo.get_messages(conversation.id)

        # 5. Save the new user message to DB and commit so it survives
        #    a provider failure.
        user_message = Message(
            conversation_id=conversation.id,
            role="user",
            content=request.message,
        )
        await self.repo.add_message(user_message)

        # Set title early (before potential LLM failure)
        if conversation.title is None:
            await self.repo.update_title(conversation, _generate_title(request.message))

        await self.db.commit()

        # 6. Build LLM messages: system prompt + context + history + new user message
        llm_messages = self._build_messages(
            existing_messages, request.message, context_string
        )

        # 7. Call LLM provider
        #    On failure: user message is already committed (for retry),
        #    no assistant message is saved, normalized error propagates.
        response_text = await self._get_provider_manager().generate_response(llm_messages)

        # 8. Save assistant response to DB
        assistant_message = Message(
            conversation_id=conversation.id,
            role="assistant",
            content=response_text,
        )
        await self.repo.add_message(assistant_message)

        # 9. Update conversation timestamp
        await self.repo.touch(conversation)

        request_tokens = sum(estimate_tokens(msg.content) for msg in llm_messages)
        response_tokens = estimate_tokens(response_text)
        history_turns = max(0, len(llm_messages) - 2)

        logger.info(
            "Aira chat | user=%s | conv=%s | farm=%s | msg_len=%d | resp_len=%d | history_turns=%d | est_tokens=%d",
            user_id,
            conversation.id,
            conversation.farm_id or "none",
            len(request.message),
            len(response_text),
            history_turns,
            request_tokens + response_tokens,
        )

        return ChatResponse(
            response=response_text,
            conversation_id=conversation.id,
        )

    async def chat_stream(
        self, user_id: str, request: ChatRequest
    ):
        """Process a chat request and yield a stream of SSE events.

        Yields dictionaries representing SSE data payloads:
            {"type": "chunk", "content": str}
            {"type": "done", "conversation_id": str}
            {"type": "error", "message": str}
        """
        try:
            # 1. Load or create conversation
            conversation = await self._resolve_conversation(user_id, request.conversation_id)

            # 2. Resolve and validate farm_id
            farm = await self._resolve_farm(user_id, conversation, request.farm_id)

            # 3. Build context
            context_string = ""
            if farm:
                unified_context = await self.context_service.build_unified_context(
                    farm, user_message=request.message
                )
                context_string = format_context(unified_context)

            # 4. Load history
            existing_messages = await self.repo.get_messages(conversation.id)

            # 5. Save user message to DB and commit
            user_message = Message(
                conversation_id=conversation.id,
                role="user",
                content=request.message,
            )
            await self.repo.add_message(user_message)

            if conversation.title is None:
                await self.repo.update_title(conversation, _generate_title(request.message))
            
            await self.db.commit()

            # 6. Build LLM messages
            llm_messages = self._build_messages(
                existing_messages, request.message, context_string
            )
            
            request_tokens = sum(estimate_tokens(msg.content) for msg in llm_messages)
            history_turns = max(0, len(llm_messages) - 2)
            
            logger.info(
                "Aira chat stream | user=%s | conv=%s | farm=%s | msg_len=%d | history_turns=%d | est_req_tokens=%d",
                user_id,
                conversation.id,
                conversation.farm_id or "none",
                len(request.message),
                history_turns,
                request_tokens,
            )

            # 7. Call LLM provider stream
            accumulated_response = []
            
            try:
                stream = self._get_provider_manager().generate_response_stream(llm_messages)
                async for chunk in stream:
                    accumulated_response.append(chunk)
                    yield {"type": "chunk", "content": chunk}
                
                response_text = "".join(accumulated_response)
                
                # 8. Complete - save to DB
                assistant_message = Message(
                    conversation_id=conversation.id,
                    role="assistant",
                    content=response_text,
                )
                await self.repo.add_message(assistant_message)
                await self.repo.touch(conversation)
                await self.db.commit()
                
                yield {"type": "done", "conversation_id": str(conversation.id)}
                
            except Exception as exc:
                # Log internal error but don't leak it to client
                logger.error("Streaming failed mid-generation: %s", exc, exc_info=True)
                yield {"type": "error", "message": "Aira could not complete the response. Please try again."}

        except Exception as exc:
            logger.error("Failed to setup chat stream: %s", exc, exc_info=True)
            yield {"type": "error", "message": "Aira could not start the response. Please try again."}

    async def get_conversations(self, user_id: str):
        """List all active conversations for a user."""
        conversations = await self.repo.get_by_user_id(user_id)
        total = await self.repo.count_by_user_id(user_id)
        return conversations, total

    async def get_conversation(self, user_id: str, conversation_id: str):
        """Get a single conversation with messages, scoped to the user."""
        conversation = await self.repo.get_by_id_and_user_id(conversation_id, user_id)
        if not conversation:
            raise NotFoundException("Conversation", conversation_id)
        return conversation

    async def delete_conversation(self, user_id: str, conversation_id: str) -> None:
        """Soft-delete a conversation, scoped to the user."""
        conversation = await self.repo.get_by_id_and_user_id(conversation_id, user_id)
        if not conversation:
            raise NotFoundException("Conversation", conversation_id)
        await self.repo.soft_delete(conversation)
        logger.info("Deleted conversation | user=%s | conv=%s", user_id, conversation_id)

    # ── Private helpers ─────────────────────────────────────────────────────

    async def _resolve_conversation(
        self, user_id: str, conversation_id: str | None
    ) -> Conversation:
        """Load an existing conversation or create a new one.

        If ``conversation_id`` is provided, validates that it exists and
        belongs to the requesting user.
        """
        if conversation_id:
            conversation = await self.repo.get_by_id_and_user_id(
                conversation_id, user_id
            )
            if not conversation:
                raise NotFoundException("Conversation", conversation_id)
            return conversation

        # Create a new conversation (no title yet — set after first message)
        conversation = Conversation(user_id=user_id)
        return await self.repo.create(conversation)

    async def _resolve_farm(
        self,
        user_id: str,
        conversation: Conversation,
        request_farm_id: str | None,
    ) -> Farm | None:
        """Resolve and validate farm_id using the locking rules.

        Returns the validated Farm object, or None if no farm context.

        Raises:
            ConflictException: If the request tries to change a locked farm_id.
            NotFoundException: If the farm doesn't exist or isn't owned by the user
                              (prevents leaking existence of other users' farms).
        """
        conv_farm_id = conversation.farm_id

        # Determine the effective farm_id
        if conv_farm_id and request_farm_id and conv_farm_id != request_farm_id:
            raise ConflictException(
                "This conversation is locked to a different farm. "
                "Start a new conversation to use a different farm."
            )

        effective_farm_id = conv_farm_id or request_farm_id

        if not effective_farm_id:
            # No farm context — continue without it
            return None

        # Validate ownership: use NotFoundException (404) to avoid
        # leaking existence of farms owned by other users.
        farm = await self.farm_repo.get_by_id(effective_farm_id)
        if not farm or farm.user_id != user_id:
            raise NotFoundException("Farm", effective_farm_id)

        # Lock the conversation to this farm (idempotent if already set)
        if not conv_farm_id:
            conversation.farm_id = effective_farm_id
            await self.db.flush()

        return farm

    @staticmethod
    def _build_messages(
        existing_messages: list[Message],
        new_user_message: str,
        context_string: str = "",
    ) -> list[AIMessage]:
        """Assemble the message list sent to the LLM provider.

        Structure:
          1. System prompt (with farm context if available)
          2. Existing conversation history (user + assistant, from DB)
          3. New user message (not yet in history)
        """
        # Build system prompt with context injection
        system_content = AIRA_SYSTEM_PROMPT
        if context_string:
            system_content = f"{AIRA_SYSTEM_PROMPT}\n\n{context_string}"

        # Estimate tokens for system content and new message
        system_tokens = estimate_tokens(system_content)
        new_msg_tokens = estimate_tokens(new_user_message)

        # Available budget for history
        available_for_history = PRACTICAL_CONTEXT_BUDGET - OUTPUT_RESERVE - system_tokens - new_msg_tokens

        if available_for_history < 0:
            logger.warning(
                "Context size exceeds practical budget. "
                "System+Context tokens: %d, New message tokens: %d, Budget: %d. "
                "No history will be included.",
                system_tokens, new_msg_tokens, PRACTICAL_CONTEXT_BUDGET
            )
            available_for_history = 0

        # Fit history using the sliding-window manager
        history_manager = HistoryManager()
        history_messages = history_manager.fit_history(
            existing_messages, available_for_history
        )

        messages: list[AIMessage] = [
            AIMessage(role="system", content=system_content),
        ]
        messages.extend(history_messages)
        messages.append(AIMessage(role="user", content=new_user_message))

        return messages
